### ISSUE TITLE
Example project templates for alternate platforms

### ISSUE THREAD

**Issue by desiderantes** [sdl2-vapi/sdl2-vapi#10]
There should be project templates for Android and iOS, to quickly start a port to these platforms. Ideally on Android, it would be a custom NDK template for Android Studio 1.3+, but we would need to wait for [Android M and it's companion tools](http://android-developers.blogspot.com/2015/05/android-m-developer-preview-tools.html) 

iOS could be harder, since dynamic linking is forbidden, so Vala apps will be GPL on that platform, and since GPL and App Store do not mix well, you'll need to release for Cydia.

These templates should probably be provided as a separate repo.

Compiling Vala + SDL2 under GNU/Linux (and cross-compiling to WIndows or OSX) is the expected way of Vala usage, since almost everybody has it's own build platform (autotools, CMake, Waf, Bake(i use this one), BSD mk, etc.), so no need for a template there.

**Comment by PedroHLC** [comment]
I already compiled Vala + SDL2 + Chipmunk2D for Android some years ago, @txasatonga did it too, my cross compile toolchain might still work though it would be better to update glib2 anyway, I still have this working demo and was working some months ago on something called "ABPP" that would easier for me to create more toolchains and keep them updated, I'm a little out of time to code my own projects.

Toolchain:
https://github.com/avalanche-games/avalanche/wiki/Useful-files

How to use the toolchain:
https://github.com/avalanche-games/avalanche/wiki/Getting-Started-%28for-Linux-users%29

A script I've used to automatize the building of the toolchain (ArchLinux only):
https://gist.github.com/PedroHLC/2192babf0f99fbf5cf6f

Making an OSX Toolchain would be even easier, but I don't have any Apple product to test it...

In this avalanche project there is an autotools makefile, which I've been using to compile for Linux/Windows/Java(JNI)/Android. And, in the example "Shooter", you can see a bash script for compiling and adding to an old Eclipse's Android project.

**Comment by txasatonga** [comment]
Yes I have already compiled for Android. See "Katamotz Hitzak" program 
at Google Store. Is Genie + SDL2.0

Gontzal

**Comment by desiderantes** [comment]
@PedroHLC  Cool, i also did something similar but with Tarnyko's tutorial. However i think that waiting a few months to redo that using Android Studio would be worth it, since official NDK support for the official IDE would increase the usefulness of a template, while still providing a command-line way of building the project.

@txasatonga Seems like a cool app, but i do not speak euskera :(

**Comment by PedroHLC** [comment]
@desiderantes Though some of our dependencies do have "Android.mk" files which allows us to easily compile and use it in NDK, most of the vala ones (like glib, gio...) do require creating custom script to do it and another one to use it. 
Another observation is that, at the end, valac creates an .so that can be used in any android project (Android Studio, Eclipse + Android ADT, and others) by adding the .so in the lib folder and creating a class to load it.

That leads me to thing of only one option we can oficially support:
1. Create an "Android.mk" for our examples, that might work as a base for the others to create theirs, that will make it much easier for them to create their .so - For that we'll have to expect the developer to already have build and install all dependencies in their own NDK.

If I finish ABPP I can also creates .zip and .tar.\* for SDL2 and GLIB, but an Android.mk for compile directly from Android NDK, or an Makefile for compiling it from a Toolchain will still be required.

`But the point is`, the IDE won't change absolutely nothing in the project building, if you're targeting SDL, the Android part of the project is just a caller/binder/wrapper for the compiled .so

**Comment by txasatonga** [comment]
Opps!! Have you seen "Nim language"? It compiles to c too (like valac) 
but with no gobject dependencies and it has yet a SDL2 binding. Woow! 
Guys this changes so fast for me!!!

Gontzal

**Comment by desiderantes** [comment]
Regarding iOS, the guys at [radare2](https://github.com/radare/radare2) have some iPhone cross compiling tutorials that can be reused.

**Comment by desiderantes** [comment]
Well, Android 6 came, and with that, Android Studio now provides a simple ndk template. Now it should be feasible to start providing a template for Android

**Comment by PedroHLC** [comment]
Sorry, I don't thing I understand why you want a template...

With Vala code is written in Vala, then with properly JNI bindings one can, after compiling, connect it code to Java, before this last point, there is no place where Android Studio can be used.
For writing the code, there is nothing Android-related needed, not even the docs.
For binding JNI, one will need to read Java docs and add them to the code.
For compiling, one will need an Android.mk and all dependencies must have it too. We do know glib doesn't have them for example. You can also use a toolchain like I do. But in both case, no IDE can be used for automatizing.
For connecting, one need to create an empty project or an empty library module, add ".so" to lib folder, create a class and add two lines of code(that will depend on the name it gave in the JNI binding) to link the ".so"

I do believe an example would be useful, but any other already written example can be ported to android by changing a few lines, that's what good about vala. So Maybe, wouldn't a tutorial on wiki, "Porting from PC to android", be a better ideia?

**Comment by desiderantes** [comment]
No longer maintained
