### ISSUE TITLE
Add Valadoc

### ISSUE THREAD

**Issue by Serranya** [sdl2-vapi/sdl2-vapi#3]
The binding should include Valadoc comments to describe its usage.

**Comment by desiderantes** [comment]
Well, there are some "merging pains" that we need to overcome first, but the binding will never be complete until there is proper Valadoc support. Also, more complex examples might be needed regarding new subsystems (GameController, Haptic, Touch & Finger, etc). however, since ideally we'll eventually commit this to vala-extra-vapis, we'll actually need to move the existing example out. Maybe create a related repo with some tutorials?

**Comment by PedroHLC** [comment]
@Serranya if you want to keep converting your valadocs to this repo, We will be more than thankful, but be prepared, that big changes can occur at any time, that's why I tried to postpone it the more I could.

**Comment by Serranya** [comment]
I will only commit valadoc for the simple parts of the API for now. Refactoring them when needed should not be too time consuming

**Comment by desiderantes** [comment]
No longer maintained
